### ISSUE TITLE
Hi, could you provide some codes about loading the deepspeed checkpoint for inference?

### ISSUE THREAD

**Issue by Yonggie** [wangjunchi/LLMSeg#4]
Hi, at deepspeed [tutorial](https://www.deepspeed.ai/tutorials/inference-tutorial/):
```py
# create the model
if args.pre_load_checkpoint:
    model = model_class.from_pretrained(args.model_name_or_path)
else:
    model = model_class()
...

import deepspeed

# Initialize the DeepSpeed-Inference engine
ds_engine = deepspeed.init_inference(model,
                                 tensor_parallel={"tp_size": 2},
                                 dtype=torch.half,
                                 checkpoint=None if args.pre_load_checkpoint else args.checkpoint_json,
                                 replace_with_kernel_inject=True)
model = ds_engine.module
output = model('Input String')
```
and there's no example to load the checkpoint.

and at the [documentation of the deepspeed](https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html), it only gives the function definition.

I got it that you provide the running script but it's highly relied on deepspeed. I tried to look deeper in the ``training.py``(readme said ``training_debug.py`` might typo?):
```py
model_engine, optimizer, train_loader, scheduler = deepspeed.initialize(
        model=model,
        model_parameters=model.parameters(),
        training_data=train_dataset,
        collate_fn=partial(
            collate_fn_new,
            tokenizer=tokenizer,
            conv_type=args.conv_type,
            use_mm_start_end=args.use_mm_start_end,
            local_rank=args.local_rank,
        ),
        config=ds_config,
    )
```
where we could not find some config to load the checkpoint?

I wonder if I could just load the checkpoint (the deepspeed checkpoint you uploaded to huggingface) and get a tiny example for inference only? Could you kindly give some advice?

**Comment by 1835969208** [comment]
@Yonggie 我遇到了相同的问题，请问你解决了吗
